## **Section 1 — Import Libraries**

In [70]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [71]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [72]:
import os

drive_path = '/content/drive/MyDrive/processed_data'

# Create the directory if it doesn't exist
os.makedirs(drive_path, exist_ok=True)

# **Section 2 — Load Dataset**

In [73]:
from google.colab import files

uploaded = files.upload()

Saving E Commerce Dataset.xlsx to E Commerce Dataset (3).xlsx

In [74]:
df = pd.read_excel(
    "E Commerce Dataset.xlsx",
    sheet_name="E Comm"
)

df.head()

,CustomerID,Churn,Tenure,PreferredLoginDevice,CityTier,WarehouseToHome,PreferredPaymentMode,Gender,HourSpendOnApp,NumberOfDeviceRegistered,PreferedOrderCat,SatisfactionScore,MaritalStatus,NumberOfAddress,Complain,OrderAmountHikeFromlastYear,CouponUsed,OrderCount,DaySinceLastOrder,CashbackAmount
0,50001,1,4.0,Mobile Phone,3,6.0,Debit Card,Female,3.0,3,Laptop & Accessory,2,Single,9,1,11.0,1.0,1.0,5.0,159.93
1,50002,1,NaN,Phone,1,8.0,UPI,Male,3.0,4,Mobile,3,Single,7,1,15.0,0.0,1.0,0.0,120.90
2,50003,1,NaN,Phone,1,30.0,Debit Card,Male,2.0,4,Mobile,3,Single,6,1,14.0,0.0,1.0,3.0,120.28
3,50004,1,0.0,Phone,3,15.0,Debit Card,Male,2.0,4,Laptop & Accessory,5,Single,8,0,23.0,0.0,1.0,3.0,134.07
4,50005,1,0.0,Phone,1,12.0,CC,Male,NaN,3,Mobile,5,Single,3,0,11.0,1.0,1.0,3.0,129.60

# **Section 3 — Remove CustomerID**

In [75]:
df.drop("CustomerID", axis=1, inplace=True)

df.head()

,Churn,Tenure,PreferredLoginDevice,CityTier,WarehouseToHome,PreferredPaymentMode,Gender,HourSpendOnApp,NumberOfDeviceRegistered,PreferedOrderCat,SatisfactionScore,MaritalStatus,NumberOfAddress,Complain,OrderAmountHikeFromlastYear,CouponUsed,OrderCount,DaySinceLastOrder,CashbackAmount
0,1,4.0,Mobile Phone,3,6.0,Debit Card,Female,3.0,3,Laptop & Accessory,2,Single,9,1,11.0,1.0,1.0,5.0,159.93
1,1,NaN,Phone,1,8.0,UPI,Male,3.0,4,Mobile,3,Single,7,1,15.0,0.0,1.0,0.0,120.90
2,1,NaN,Phone,1,30.0,Debit Card,Male,2.0,4,Mobile,3,Single,6,1,14.0,0.0,1.0,3.0,120.28
3,1,0.0,Phone,3,15.0,Debit Card,Male,2.0,4,Laptop & Accessory,5,Single,8,0,23.0,0.0,1.0,3.0,134.07
4,1,0.0,Phone,1,12.0,CC,Male,NaN,3,Mobile,5,Single,3,0,11.0,1.0,1.0,3.0,129.60

# **Section 4 — Handle Missing Values**

In [76]:
df.isnull().sum()

Churn                            0
Tenure                         264
PreferredLoginDevice             0
CityTier                         0
WarehouseToHome                251
PreferredPaymentMode             0
Gender                           0
HourSpendOnApp                 255
NumberOfDeviceRegistered         0
PreferedOrderCat                 0
SatisfactionScore                0
MaritalStatus                    0
NumberOfAddress                  0
Complain                         0
OrderAmountHikeFromlastYear    265
CouponUsed                     256
OrderCount                     258
DaySinceLastOrder              307
CashbackAmount                   0
dtype: int64

**Numerical Columns**

In [77]:
numerical_columns = df.select_dtypes(include=np.number).columns

numerical_columns

Index(['Churn', 'Tenure', 'CityTier', 'WarehouseToHome', 'HourSpendOnApp',
       'NumberOfDeviceRegistered', 'SatisfactionScore', 'NumberOfAddress',
       'Complain', 'OrderAmountHikeFromlastYear', 'CouponUsed', 'OrderCount',
       'DaySinceLastOrder', 'CashbackAmount'],
      dtype='object')

In [78]:
for col in numerical_columns:

    if df[col].isnull().sum() > 0:

        df[col].fillna(df[col].median(), inplace=True)

**Categorical Columns**

In [79]:
categorical_columns = df.select_dtypes(include="object").columns

categorical_columns

Index(['PreferredLoginDevice', 'PreferredPaymentMode', 'Gender',
       'PreferedOrderCat', 'MaritalStatus'],
      dtype='object')

In [80]:
for col in categorical_columns:

    if df[col].isnull().sum() > 0:

        df[col].fillna(df[col].mode()[0], inplace=True)

In [81]:
df.isnull().sum()

Churn                          0
Tenure                         0
PreferredLoginDevice           0
CityTier                       0
WarehouseToHome                0
PreferredPaymentMode           0
Gender                         0
HourSpendOnApp                 0
NumberOfDeviceRegistered       0
PreferedOrderCat               0
SatisfactionScore              0
MaritalStatus                  0
NumberOfAddress                0
Complain                       0
OrderAmountHikeFromlastYear    0
CouponUsed                     0
OrderCount                     0
DaySinceLastOrder              0
CashbackAmount                 0
dtype: int64

# **Section 5 — Separate Features & Target**

In [82]:
X = df.drop("Churn", axis=1)

y = df["Churn"]

In [83]:
print(X.shape)

print(y.shape)

(5630, 18)
(5630,)

# **Section 6 — Train/Test Split**

In [84]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

# **Section 7 — Encode Categorical Features**

In [85]:
X.select_dtypes(include="object").columns

Index(['PreferredLoginDevice', 'PreferredPaymentMode', 'Gender',
       'PreferedOrderCat', 'MaritalStatus'],
      dtype='object')

**Encode using LabelEncoder:**

In [86]:
encoders = {}

for col in X_train.select_dtypes(include="object").columns:

    le = LabelEncoder()

    X_train[col] = le.fit_transform(X_train[col])

    X_test[col] = le.transform(X_test[col])

    encoders[col] = le

In [87]:
X.head()

,Tenure,PreferredLoginDevice,CityTier,WarehouseToHome,PreferredPaymentMode,Gender,HourSpendOnApp,NumberOfDeviceRegistered,PreferedOrderCat,SatisfactionScore,MaritalStatus,NumberOfAddress,Complain,OrderAmountHikeFromlastYear,CouponUsed,OrderCount,DaySinceLastOrder,CashbackAmount
0,4.0,Mobile Phone,3,6.0,Debit Card,Female,3.0,3,Laptop & Accessory,2,Single,9,1,11.0,1.0,1.0,5.0,159.93
1,9.0,Phone,1,8.0,UPI,Male,3.0,4,Mobile,3,Single,7,1,15.0,0.0,1.0,0.0,120.90
2,9.0,Phone,1,30.0,Debit Card,Male,2.0,4,Mobile,3,Single,6,1,14.0,0.0,1.0,3.0,120.28
3,0.0,Phone,3,15.0,Debit Card,Male,2.0,4,Laptop & Accessory,5,Single,8,0,23.0,0.0,1.0,3.0,134.07
4,0.0,Phone,1,12.0,CC,Male,3.0,3,Mobile,5,Single,3,0,11.0,1.0,1.0,3.0,129.60

# **Section 8 — Feature Scaling**

In [88]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

**Convert back to a DataFrame:**

In [89]:

X_train = pd.DataFrame(
    X_train,
    columns=X.columns
)

X_test = pd.DataFrame(
    X_test,
    columns=X.columns
)

**Check the shapes:**

In [90]:
print("X_train :", X_train.shape)

print("X_test :", X_test.shape)

print("y_train :", y_train.shape)

print("y_test :", y_test.shape)

X_train : (4504, 18)
X_test : (1126, 18)
y_train : (4504,)
y_test : (1126,)

# **Section 9 — Save Processed Data**

In [93]:
processed_train = X_train.copy()
processed_train["Churn"] = y_train.values

processed_test = X_test.copy()
processed_test["Churn"] = y_test.values

processed_train.to_csv(os.path.join(drive_path, "train_processed.csv"), index=False)

processed_test.to_csv(os.path.join(drive_path, "test_processed.csv"), index=False)
print("✅ Processed datasets saved successfully!")

✅ Processed datasets saved successfully!